global:
  resolve_timeout: 5m

route:
  receiver: discord

receivers:
  - name: 'discord'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1397150241140113448/KZaLSwhmmaGuYxFomEjqOiBiEHQrvXdR5vsO0mhpVpWTlBJUl8df4TmSApIGBF6zD2Bx'
        send_resolved: true
