global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['dokploy:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
