global:
  scrape_interval: 10s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'docker-swarm-nodes'
    static_configs:
      - targets:
          - '10.100.4.104:9323'
          - '10.100.4.105:9323'
          - '10.100.4.106:9323'
